<a href="https://colab.research.google.com/github/LillianaU/Arreglos_12_08_2025/blob/main/vectores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

los vectores son reserva de memoria para almacenar  informacion, solo puede ser de un tuipo, si es numerico , es numerico, si es texto , debe continuar siendo texto , esto aplica para las matrices.
Los arreglos son identificadores estatifos, esto significa que es otra forma de definir , variables y constantes.

In [1]:
import numpy as np # np es un alias para recortar el nombre de numpy
vector = np.array([1, 2, 3, 4, 5]) # Creamos un vector de numpy
print(vector) # Imprimimos el vector
# quiero imprimir el tercer elemento del vector
print(vector[2]) # Imprimimos el tercer elemento del vector (índice 2)
""" los vectores no son como las listas, no tienen un método append() para agregar elementos
y no tienen un método pop() para eliminar elementos, pero sí tienen un método reshape() para cambiar su forma , adicionalmente despues de creado no se puede cambiar el tamaño del vector """
vector1 =np.zeros(5) # Creamos un vector de ceros de tamaño 5
print(vector1) # Imprimimos el vector de ceros
vector2 = np.ones(5) # Creamos un vector de unos de tamaño 5
print(vector2) # Imprimimos el vector de unos
vector3 = np.arange(1,10) # Creamos un vector derango de 1 al 10
print("rango",vector3) # Imprimimos el vector de números rango
vector4 = np.linspace(1, 10, 5) # Creamos un vector de 5 números entre 1 y 10
print("linspace",vector4) # Imprimimos el vector de números linspace
vector5 = np.random.rand(10) # Creamos un vector de 5 números aleatorios entre 0 y 10
print("random",vector5) # Imprimimos el vector de números aleatorios
vector6= np.random.randint(1,10,10) # Creamos un vector de 5 números aleatorios entre 0 y 10
print("randint",vector6) # Imprimimos el vector de números aleatorios
# Creamos un vector de 5 números aleatorios entre 0 y 10

[1 2 3 4 5]
3
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
rango [1 2 3 4 5 6 7 8 9]
linspace [ 1.    3.25  5.5   7.75 10.  ]
random [0.49627817 0.04522444 0.49784955 0.96471387 0.61513495 0.02127387
 0.6788536  0.80396711 0.54776155 0.72968377]
randint [8 6 8 7 4 6 4 4 8 6]
